[device]
wifi.scan-rand-mac-address=no
# Prevent NetworkManager from managing ethernet port
match-device=interface-name:eth0
managed=0

[connection]
wifi.cloned-mac-address=permanent
ethernet.cloned-mac-address=permanent