[Service]
# Set maximum wait time to 15 seconds for network connectivity (network-online.target).
# This is used to address long online connectivity (e.g. no Wifi and Ethernet available),
# which can cause delays in booting ROS2 bumperbot services.
ExecStart=
ExecStart=/usr/bin/nm-online -s -q --timeout=15